AWSTemplateFormatVersion: "2010-09-09"
Description: Security Stack for RaiseTech Lecture13

Parameters:
  MyIP:
    Description: IP address allowed to access EC2
    Type: String
    Default: 0.0.0.0/0

Resources:
  # EC2のセキュリティグループ
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Security Group
      GroupName: !Sub
        - ${ExportedBaseName}-EC2-SG
        - ExportedBaseName: !ImportValue ExportedBaseName
      VpcId: !ImportValue ExportedVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref MyIP
          #SourceSecurityGroupId: !Ref ALBSecurityGroup
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref MyIP
      Tags:
        - Key: Name
          Value: !Sub
            - ${ExportedBaseName}-EC2-SG
            - ExportedBaseName: !ImportValue ExportedBaseName

  # ALBのセキュリティグループ
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB Security Group
      GroupName: !Sub
        - ${ExportedBaseName}-ALB-SG
        - ExportedBaseName: !ImportValue ExportedBaseName
      VpcId: !ImportValue ExportedVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub
            - ${ExportedBaseName}-ALB-SG
            - ExportedBaseName: !ImportValue ExportedBaseName

  # RDSのセキュリティグループ
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: RDS Security Group
      GroupName: !Sub
        - ${ExportedBaseName}-RDS-SG
        - ExportedBaseName: !ImportValue ExportedBaseName
      VpcId: !ImportValue ExportedVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup
      Tags:
        - Key: Name
          Value: !Sub
            - ${ExportedBaseName}-RDS-SG
            - ExportedBaseName: !ImportValue ExportedBaseName

  # IAMロール
  S3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub
        - ${ExportedBaseName}-S3Role
        - ExportedBaseName: !ImportValue ExportedBaseName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Path: "/"
      Tags:
        - Key: Name
          Value: !Sub
            - ${ExportedBaseName}-S3Role
            - ExportedBaseName: !ImportValue ExportedBaseName

  # IAMインスタンスプロファイル
  S3InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      InstanceProfileName: !Sub
        - ${ExportedBaseName}-S3InstanceProfile
        - ExportedBaseName: !ImportValue ExportedBaseName
      Roles:
        - !Ref S3Role

Outputs:
  ALBSecurityGroupId:
    Description: This is the ALB security group ID
    Value: !Ref ALBSecurityGroup
    Export:
      Name: ExportedALBSecurityGroupId

  EC2SecurityGroupId:
    Description: This is the EC2 security group ID
    Value: !Ref EC2SecurityGroup
    Export:
      Name: ExportedEC2SecurityGroupId

  RDSSecurityGroupId:
    Description: This is the RDS security group ID
    Value: !Ref RDSSecurityGroup
    Export:
      Name: ExportedRDSSecurityGroupId

  S3InstanceProfile:
    Description: This is the S3 instance profile
    Value: !Ref S3InstanceProfile
    Export:
      Name: ExportedS3InstanceProfile
